Repository hack4bengal/s3, pull requests merged in 2023-10, with the labels that each got.

#24 fix: changes to hero section buttons
  src/sections/WelcomeSection/WelcomeSection.jsx
Labels: bug, hacktoberfest

#34 fix: changes to judges uri and removed doge data
  src/assets/data/judgesData.js
  src/components/navbar/Navbar.jsx
  src/components/navbar/dropdown/Dropdown.jsx
  src/sections/JudgesSection/JudgesSection.jsx
Labels: bug

#26 fix: changes to testimonial linkedin ids
  src/assets/data/testimonialData.js
Labels: bug, changes needed

#32 fix: changes to gap between nav items
  src/components/navbar/Navbar.jsx
Labels: bug

#27 feat: adding vite to the existing app
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/components/InfiniteCarouselSection/InfiniteCarousel.css
  src/components/faq/AnswerAccordian.jsx
  src/components/faq/QuestionAccordian.jsx
  src/components/navbarTeam/NavbarTeam.jsx
  src/components/timer/Timer.jsx
  src/index.jsx
  src/pages/Terms/Terms.jsx
  src/pages/coc/CodeofConduct.jsx
  src/pages/eventTcp/EventTcp.jsx
  src/pages/privacyPolicy/PrivacyPolicy.jsx
  src/sections/event/Event.jsx
  vite.config.js
Labels: enhancement, changes needed

#37 Fixed existing contributing guidelines
  CONTRIBUTING.md
Labels: documentation

#40 Bug: Remove first two logos #38
  src/pages/brand/BrandAssetsData.js
Labels: bug, changes needed
